services:
    # écouteur d'évènements de Doctrine: 
    # met à jour la date de modification des candidatures lorsque des entités liées sont modifiées
    candidatures.listener1:
        class: NomayaCandidaturesBundle\EventListener\CandidatureUpdater
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

parameters:
    candidature.delay:      15