<?php

namespace NomayaCandidaturesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends EntityRepository
{
	public function findOneWithCandidatures($id){
		return $this->getEntityManager()
		            ->createQuery(
		                'SELECT e FROM CandidaturesBundle:Entreprise e 
		                LEFT JOIN e.candidatures c
		                WHERE e.id = :id
		                '
		            )
		            ->setParameter('id', $id)
		            ->getSingleResult();
	}

	public function findAllOrderedBy($column, $direction, $search = null){
		$query = array();
		$query[] = 'SELECT e FROM CandidaturesBundle:Entreprise e';
        if (!is_null($search))
        {
            $query[] = 'WHERE e.name LIKE :search';
            $query[] = 'OR e.tel LIKE :search';
            $query[] = 'OR e.email LIKE :search';
            $query[] = 'OR e.website LIKE :search';
            $query[] = 'OR e.city LIKE :search';
        }
		$query[] = 'ORDER BY e.'.$column.' '.$direction;
		$dql = join(' ', $query);
		$em =  $this->getEntityManager()
                    ->createQuery($dql);
        if(!is_null($search))
        	$em->setParameter('search', '%'.$search.'%');
		return $em->getResult();		
	}

	public function findAllOrderedById(){
		return $this->findAllOrderedBy('id', 'DESC');
	}
}
