<?php

namespace NomayaCandidaturesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvenementRepository extends EntityRepository
{
}
