<?php

namespace Nomaya\Candidatures\CandidaturesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	/**
	 * recherche suivant un mot passé en paramètre
	**/
	public function findAllWithRelated($search = null)
	{
		$query = array();
		$query[] = 'SELECT c, en FROM CandidaturesBundle:Contact c';
		$query[] = 'JOIN c.entreprise en';
		if (!is_null($search))
		{
			$query[] = 'WHERE c.name LIKE :search';
			$query[] = 'OR c.firstName LIKE :search ';
			$query[] = 'OR c.email LIKE :search';
			$query[] = 'OR c.tel LIKE :search';
			$query[] = 'OR c.function LIKE :search';
			$query[] = 'OR en.name LIKE :search';
		}
		$dql = join(' ', $query);
		$em =  $this
				->getEntityManager()
	            ->createQuery($dql);
	    if (!is_null($search))
	    	$em->setParameter('search', '%'.$search.'%');
        return $em->getResult();	

	}

}
