<?php

namespace Nomaya\Candidatures\CandidaturesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{

	public function findAllWithRelated()
	{
		return  $this->getEntityManager()
                    	->createQuery('SELECT d, ev, c FROM CandidaturesBundle:Document d
                    				LEFT JOIN d.evenement ev
                    				LEFT JOIN d.candidature c')
                    	->getResult();		
	}
}
